-- AlterTable
ALTER TABLE `task` ADD COLUMN `courseSummary` VARCHAR(191) NULL,
    ADD COLUMN `emailBody` VARCHAR(191) NULL,
    ADD COLUMN `recipient` VARCHAR(191) NULL,
    ADD COLUMN `type` ENUM('DEFAULT', 'EMAIL', 'COURSE') NOT NULL DEFAULT 'DEFAULT';
